// lib/core/database/isar_database_service.dart
import 'dart:async';
import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:isar/isar.dart';
import 'package:path_provider/path_provider.dart';

// ── Active feature schemas (generated by build_runner) ──────────
// bookmarks_v2 — wired to bookmark provider
import '../../features/bookmarks/data/models/bookmark_entity.dart';
// notes_v2 — wired to note provider
import '../../features/notes/data/models/note_entity.dart';

// ── Core database schemas (generated by build_runner) ───────────
// Only importing schemas NOT already defined in feature files.
// BookmarkEntity and PersonalNoteEntity from database_models.dart
// are intentionally excluded — superseded by features equivalents.
import 'database_models.dart'
    show
        ReaderProgressEntity,
        ReaderProgressEntitySchema,
        PdfProgressEntity,
        PdfProgressEntitySchema,
        UserProfileEntity,
        UserProfileEntitySchema;

// ─────────────────────────────────────────────
// MARK: — EXCEPTION
// ─────────────────────────────────────────────

class IsarDatabaseException implements Exception {
  final String  message;
  final Object? cause;
  const IsarDatabaseException({required this.message, this.cause});
  @override
  String toString() =>
      'IsarDatabaseException: $message'
      '${cause != null ? " — cause: $cause" : ""}';
}

// ─────────────────────────────────────────────
// MARK: — ISAR DATABASE SERVICE
// ─────────────────────────────────────────────

class IsarDatabaseService {
  // ── Singleton ─────────────────────────────────
  static final IsarDatabaseService _instance =
      IsarDatabaseService._internal();
  factory IsarDatabaseService()           => _instance;
  static IsarDatabaseService get instance => _instance;
  IsarDatabaseService._internal();

  static const String _dbName = 'law_briefly_v1';

  // ── State ─────────────────────────────────────
  Isar?             _isar;
  bool              _initialized   = false;
  Completer<void>?  _initCompleter;

  bool get isInitialized => _initialized && (_isar?.isOpen ?? false);
  bool get isOpen        => _isar?.isOpen ?? false;

  // ─────────────────────────────────────────────
  // MARK: — INITIALIZE
  // ─────────────────────────────────────────────

  Future<void> initialize({
    String? dbName,
    bool    inspector  = false,
    bool    compact    = true,
  }) async {
    if (_initialized && (_isar?.isOpen ?? false)) return;

    if (_initCompleter != null) {
      return _initCompleter!.future;
    }

    _initCompleter = Completer<void>();

    try {
      final dir = await _resolveDirectory();

      // ── REGISTERED SCHEMAS ─────────────────────
      //
      // BookmarkEntity     → features/bookmarks  → 'bookmarks_v2'
      // NoteEntity         → features/notes      → 'notes_v2'
      // ReaderProgressEntity → core/database     → 'reader_progress'
      // PdfProgressEntity    → core/database     → 'pdf_progress'
      // UserProfileEntity    → core/database     → 'user_profiles'
      //
      // DO NOT register:
      //   BookmarkEntity from database_models.dart    (duplicate class name)
      //   PersonalNoteEntity from database_models.dart (orphaned — use NoteEntity)
      final List<CollectionSchema<dynamic>> schemas = [
        BookmarkEntitySchema,       // features/bookmarks/data/models/bookmark_entity.dart
        NoteEntitySchema,           // features/notes/data/models/note_entity.dart
        ReaderProgressEntitySchema, // core/database/database_models.dart
        PdfProgressEntitySchema,    // core/database/database_models.dart
        UserProfileEntitySchema,    // core/database/database_models.dart
      ];

      _isar = await Isar.open(
        schemas,
        directory: dir.path,
        name:      dbName ?? _dbName,
        inspector: inspector && kDebugMode,
        compactOnLaunch:
            compact ? const CompactCondition(minFileSize: 512 * 1024) : null,
      );

      _initialized = true;
      _initCompleter!.complete();

      debugPrint(
        '[IsarDatabaseService] ✅ Opened "${dbName ?? _dbName}" '
        'at ${dir.path} (${schemas.length} schemas registered)',
      );
    } catch (e, st) {
      _initialized = false;
      _initCompleter!.completeError(
          IsarDatabaseException(message: 'Initialization failed.', cause: e),
          st);
      _initCompleter = null;
      debugPrint('[IsarDatabaseService] ❌ Init failed: $e');
      rethrow;
    } finally {
      if (_initCompleter?.isCompleted ?? false) {
        _initCompleter = null;
      }
    }
  }

  // ─────────────────────────────────────────────
  // MARK: — GET DATABASE
  // ─────────────────────────────────────────────

  Future<Isar> getDatabase() async {
    if (!_initialized || !(_isar?.isOpen ?? false)) {
      await initialize();
    }
    if (_isar == null || !_isar!.isOpen) {
      throw const IsarDatabaseException(
        message: 'Database is not open after initialization.',
      );
    }
    return _isar!;
  }

  /// Synchronous accessor — throws if not initialized.
  Isar get isar {
    if (_isar == null || !_isar!.isOpen) {
      throw const IsarDatabaseException(
        message: 'IsarDatabaseService not initialized. '
            'Call initialize() in main() before use.',
      );
    }
    return _isar!;
  }

  /// Returns null if not initialized (safe accessor).
  Isar? get isarOrNull => (_isar?.isOpen ?? false) ? _isar : null;

  // ─────────────────────────────────────────────
  // MARK: — CLOSE
  // ─────────────────────────────────────────────

  Future<void> close() async {
    if (_isar == null || !(_isar?.isOpen ?? false)) {
      debugPrint('[IsarDatabaseService] Already closed.');
      return;
    }
    try {
      await _isar!.close();
      _isar         = null;
      _initialized  = false;
      debugPrint('[IsarDatabaseService] Closed.');
    } catch (e) {
      throw IsarDatabaseException(
          message: 'Failed to close database.', cause: e);
    }
  }

  // ─────────────────────────────────────────────
  // MARK: — CLEAR ALL DATA
  // ─────────────────────────────────────────────

  Future<void> clearAllData() async {
    final db = await getDatabase();
    await db.writeTxn(() => db.clear());
    debugPrint('[IsarDatabaseService] All data cleared.');
  }

  // ─────────────────────────────────────────────
  // MARK: — DATABASE SIZE
  // ─────────────────────────────────────────────

  Future<int> getDatabaseSizeBytes() async {
    final db  = await getDatabase();
    final dir = await _resolveDirectory();
    final file = File('${dir.path}/${db.name}.isar');
    if (!file.existsSync()) return 0;
    return file.lengthSync();
  }

  // ─────────────────────────────────────────────
  // MARK: — PRIVATE
  // ─────────────────────────────────────────────

  Future<Directory> _resolveDirectory() async {
    if (Platform.isAndroid || Platform.isIOS) {
      return getApplicationDocumentsDirectory();
    }
    final support = await getApplicationSupportDirectory();
    final dir     = Directory('${support.path}/law_briefly_db');
    if (!dir.existsSync()) await dir.create(recursive: true);
    return dir;
  }
}